/// <reference types="nativewind/types" />
// expo-env.d.ts carries this too, but it is generated by `expo start` and gitignored —
// referencing it here keeps `npm run typecheck` working on a fresh clone.
/// <reference types="expo/types" />
